<?php

function islandora_scholar_templates_ir_citationCModel_islandora_view_object_alter($object, &$display) {
  unset($display['citation.tab']['citation_select']);
  unset($display['citation.tab']['prefix']);
  unset($display['citation.tab']['preview']);
  unset($display['citation.tab']['pdf_download']);
  unset($display['citation.tab']['metadata']);
  unset($display['citation.tab']['suffix']);
  unset($display['citation.tab']['citation']);  
}

function islandora_scholar_templates_ir_citationCModel_islandora_view_object($object) {
  $display = islandora_scholar_get_view($object);
  $output = theme('islandora_scholar_citation', array('islandora_object' => $object, 'display' => $display));
  return array('citation.tab' => $output);
}

function islandora_scholar_templates_ir_thesisCModel_islandora_view_object_alter($object, &$display) {
  unset($display['citation.tab']['citation_select']);
  unset($display['citation.tab']['prefix']);
  unset($display['citation.tab']['preview']);
  unset($display['citation.tab']['pdf_download']);
  unset($display['citation.tab']['metadata']);
  unset($display['citation.tab']['suffix']);
  unset($display['citation.tab']['citation']);
}

function islandora_scholar_templates_ir_thesisCModel_islandora_view_object($object) {
  $display = islandora_scholar_get_view($object);
  $output = theme('islandora_scholar_thesis', array('islandora_object' => $object, 'display' => $display));
  return array('citation.tab' => $output);
}

function islandora_scholar_templates_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_scholar_citation' => array(
      'path' => drupal_get_path('module', 'islandora_scholar_templates').'/theme',
      'template' => 'islandora-scholar-citation',
      'variables' => array('islandora_object' => NULL, 'display' => NULL),
    ),
    'islandora_scholar_thesis' => array(
      'path' => drupal_get_path('module', 'islandora_scholar_templates').'/theme',
      'template' => 'islandora-scholar-thesis',
      'variables' => array('islandora_object' => NULL, 'display' => NULL),
    ),
  );  
}
